language: php

branches:
  except:
    - /^release-.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - laminas-mkdoc-theme

env:
  global:
    - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
    - SITE_URL: https://docs.laminas.dev/laminas-serializer
    - GH_USER_NAME: "Matthew Weier O'Phinney"
    - GH_USER_EMAIL: matthew@weierophinney.net
    - GH_REF: github.com/laminas/laminas-serializer.git
    - secure: "Eus59mQXnKuHFWh7olBeAoc3e2AHp9z2IvJuZx6zcLO1HBu7+iTXhZL74jwbFW3h6g+2jgIyLIr81aGNLwpxQfZKhWRMM2O8kQIMnz+svRh2RC30zs2bcuDyoHr086lQEcOXMGcnMl52X00DIr4jMj7sJ1gVe+g9aZpoU4Qq/4J2d+bKKnN802e+NBzsgIhY+NUmffZpb5s/RWejhR2HCbyfQrsNEEmXO/qHOwJNxlD4bG1ckXDtidFBepfEJT+/sbJkrkNTibOoxjyZyfADt8YOujktEyYBAgoCf5cv/Erw0lQO5lwnXI8O6Cp86x9zJtxo2Vm6RkIa5fUR6qb/Difta58OXHzXJsCrPTfTiV/SKWr31Rfsd3HlJhwd3aogsF5VBBGKrNKZ+avXbuq++QThXwkE+XUmxKHsbFpct7q+AP1CkOUefEKu/AayHnJulUpiL4JzG/BvjSC8rVAUlsXf51gVL/rTVjqbR5YCmoxGBSORHl4WFgOmq9D2T4TKEhGgsQBF9IB3N6VVc0TE+S5XVSwkHdd1d76VpasYeNO3UNEstfc+R0kWYGpmXVmvubBLX3i/Zv/k0LwfEaSUl06MK+Xnc0twx8da8cd7WDChP1YAfJn531msQjgjWtz+c3E3EiFExILvOnPotEj+S0tEU/GPVXkiQKiJwojWozI="

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - DEPS=lowest
    - php: 5.6
      env:
        - DEPS=latest
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
        - TEST_COVERAGE=true
    - php: 7
      env:
        - DEPS=lowest
    - php: 7
      env:
        - DEPS=latest
        - CS_CHECK=true
    - php: hhvm
      env:
        - DEPS=lowest
    - php: hhvm
      env:
        - DEPS=locked
    - php: hhvm
      env:
        - DEPS=latest
  allow_failures:
    - php: hhvm

notifications:
  email: false

before_install:
  - travis_retry composer self-update
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS satooshi/php-coveralls:^1.0 ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer show --installed

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then wget -O theme-installer.sh "https://raw.githubusercontent.com/laminas/laminas-mkdoc-theme/master/theme-installer.sh" ; chmod 755 theme-installer.sh ; ./theme-installer.sh ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./laminas-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer upload-coverage ; fi
