docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Intro: intro.md
    - Adapters: adapter.md
site_name: laminas-serializer
site_description: laminas-serializer
repo_url: 'https://github.com/laminas/laminas-serializer'
